guild:
  #maximum length of a full name
  name-max-length: 22
  #minimal length of a full name
  name-min-length: 4
  #maximum length of a tag
  tag-max-length: 4
  #minimal length of a tag
  tag-min-length: 2
  #maximal number of members
  max-members: 15

cuboid:
  #initial size the cuboids are created with
  initial-size: 20
  #minimum distance between cuboids in X/Y axis
  minimum-distance: 200

field:
  #density of the dome
  dome-particle-density: 1
  #amount of blocks from which the dome is visible
  dome-render-distance: 30
  #density of the wall
  wall-particle-density: 2
  #amount of blocks from which the wall is visible
  wall-render-distance: 5
  #initial HP of the field
  initial-energy: 10000000
  #amount of energy to be subtracted
  passive-drain-amount: 20
  #how often passive drain should trigger in ticks
  passive-drain-delay: 20
  #how much damage should be inflicted on the field by an arrow
  arrow-damage: 1200
  #how much damage should be inflicted on the field by tnt
  tnt-damage: 12000
  #conversion rates between items and energy
  #check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for material names
  energy-fuel:
    #MATERIAL_NAME: ENERGY_AMOUNT
    DIAMOND: 100000
    EMERALD: 200000

gui:
  main-gui-title: '&2%guild%'


# Information for the MYSQL data storage:
#  > hostname - host of the database
#  > port - port of the database
#  > database - name of the database
#  > username - username for the database
#  > password - password for the database
#  > tableName - prefix of the database tables used by the plugin
#  > useSSL - whether to use SSL when connecting to the database
#  > poolSize - number of database connections reserved by the plugin
#  > connectionTimeout - database connection timeout delay, in milliseconds
#  > autoSave - how often will the data be saved, in seconds
mysql:
  hostname: "127.0.0.1"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
  tableName: "bfactions_"
  useSSL: true
  poolSize: 5
  connectionTimeout: 20000
  autoSave: 600