guild:
  #minimum distance between cuboids in X/Y axis
  minimum-distance: 200
  #/bf home delay in seconds
  home-tp-delay: 5

field:
  #render distance of the bossbar outside the border
  hp-bar-render-distance: 30
  #density of the dome
  dome-particle-density: 0.5
  #amount of blocks from which the dome is visible
  dome-render-distance: 30
  #amount of blocks from which the dome is visible (horizontally)
  dome-render-distance-horizontal: 10
  #density of the wall
  border-particle-density: 1
  #amount of blocks from which the wall is visible
  border-render-distance: 5
  #amount of blocks from which the wall is visible (horizontally)
  border-render-distance-horizontal: 5
  #the amount of seconds the players are allowed to mine/interact with foreign region after the field is knocked down
  field-knockdown-timeout: 300
  #how often passive drain should trigger in ticks
  passive-drain-delay: 20
  #how much damage should be inflicted on the field by an arrow
  arrow-damage: 1200
  #how much damage should be inflicted on the field by tnt
  tnt-damage: 12000
  #conversion rates between items and energy
  #check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for material names
  energy-fuel:
    #MATERIAL_NAME: ENERGY_AMOUNT
    DIAMOND: 100000
    EMERALD: 200000
  #the energy the field starts with
  initial-configuration:
    initial-energy: 10000000

  # In this section you can specify items which make the field undamageable
  # in this example "test" is the item id
  # to set it execute /bf setitem boost-undamageable-test
  # to get it execute /bf giveitem boost-undamageable-test
  # you can use %time% as a placeholder so it will show actual time left
  # you can also create your custom ids and delete the test one
  # the number is the time (in seconds) for how long can the item make your field undamageable
  boost-undamageable-items:
    test: 600
    some-id: 666

time-format:
  days: 'd'
  hours: 'h'
  minutes: 'm'
  seconds: 's'
  milliseconds: 'ms'

hologram:
  beacon:
    - 'test'

gui:
  main-gui-title: '&a%guild%'
  invites-gui-title: 'Invites %page%/%pages%'
  manage-members-gui-title: 'Members %page%/%pages%'
  manage-member-gui-title: '%player%'
  field-upgrade-gui-title: 'Energy upgrades'
  region-upgrade-gui-title: 'Size upgrades'
  boost-undamageable-gui-title: 'Undamageable boosts'
  confirmation-gui-title: 'Confirm action'


# Information for the MYSQL data storage:
#  > hostname - host of the database
#  > port - port of the database
#  > database - name of the database
#  > username - username for the database
#  > password - password for the database
#  > tableName - prefix of the database tables used by the plugin
#  > useSSL - whether to use SSL when connecting to the database
#  > poolSize - number of database connections reserved by the plugin
#  > connectionTimeout - database connection timeout delay, in milliseconds
#  > autoSave - how often will the data be saved, in seconds
mysql:
  hostname: "127.0.0.1"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
  tableName: "bfactions_"
  useSSL: true
  poolSize: 5
  connectionTimeout: 20000
  autoSave: 600