guild:
  #maximum length of a full name
  name-max-length: 22
  #minimal length of a full name
  name-min-length: 4
  #maximum length of a tag
  tag-max-length: 4
  #minimal length of a tag
  tag-min-length: 2
  #maximal number of members
  max-members: 15
  #minimum distance between cuboids in X/Y axis
  minimum-distance: 200

field:
  #render distance of the bossbar outside the border
  hp-bar-render-distance: 30
  #density of the dome
  dome-particle-density: 0.5
  #amount of blocks from which the dome is visible
  dome-render-distance: 30
  #density of the wall
  border-particle-density: 1
  #amount of blocks from which the wall is visible
  border-render-distance: 5
  #how often passive drain should trigger in ticks
  passive-drain-delay: 20
  #how much damage should be inflicted on the field by an arrow
  arrow-damage: 1200
  #how much damage should be inflicted on the field by tnt
  tnt-damage: 12000
  #conversion rates between items and energy
  #check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for material names
  energy-fuel:
    #MATERIAL_NAME: ENERGY_AMOUNT
    DIAMOND: 100000
    EMERALD: 200000
  #upgrades of the field
  #the first tier is the initial configuration and should contain "initial-energy" field
  #the tiers are read in order as is in this file, the key of each tier should be unique
  initial-configuration:
    max-energy: 10000000
    initial-energy: 1000000
    radius: 20
    passive-drain-amount: 20

  energy-upgrades:
    1:
      max-energy: 15000000
      cost: 5000000
    2:
      max-energy: 20000000
      cost: 5000000

  size-upgrades:
    1:
      radius: 25
      passive-drain-amount: 30
      cost: 5000000
    2:
      radius: 30
      passive-drain-amount: 40
      cost: 10000000

  # In this section you can specify items which make the field undamageable
  # in this example "test" is the item id
  # to set it execute /bf setitem undamageable-test
  # to get it execute /bf giveitem undamageable-test
  # you can use %time% as a placeholder so it will show actual time left
  # you can also create your custom ids and delete the test one
  # the number is the time (in seconds) for how long can the item make your field undamageable
  undamageable-items:
    test: 600
    some-id: 666


gui:
  main-gui-title: '&2%guild%'

# Information for the MYSQL data storage:
#  > hostname - host of the database
#  > port - port of the database
#  > database - name of the database
#  > username - username for the database
#  > password - password for the database
#  > tableName - prefix of the database tables used by the plugin
#  > useSSL - whether to use SSL when connecting to the database
#  > poolSize - number of database connections reserved by the plugin
#  > connectionTimeout - database connection timeout delay, in milliseconds
#  > autoSave - how often will the data be saved, in seconds
mysql:
  hostname: "127.0.0.1"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
  tableName: "bfactions_"
  useSSL: true
  poolSize: 5
  connectionTimeout: 20000
  autoSave: 600